"""Guarded Home Assistant hardware writer for the go-e EV charger."""

from __future__ import annotations

import logging
import math
from datetime import UTC, datetime, timedelta
from typing import Any

from .config import EvSettings
from .ha_client import HomeAssistantError

_LOGGER = logging.getLogger(__name__)
EV_CONTROL_VERSION = "2026-10-10-ev-control-v2"
EV_CONTROL_STATUS_ENTITY = "sensor.energy_manager_ev_control_status"
_PHASE_SWITCH_DELAY_SECONDS = 3.0
_FORCE_DONT_CHARGE = "1"
_FORCE_CHARGE = "2"
_PHASE_SINGLE = "1"
_PHASE_THREE = "2"
_CURRENT_TOLERANCE_A = 0.1
_MAX_COMMAND_ATTEMPTS = 3
_MAX_WRITE_ERRORS = 3
_FAULT_COOLDOWN_SECONDS = 10.0


class EvHardwareController:
    """Translate generic EV power commands into safe go-e Home Assistant writes."""

    def __init__(
        self,
        client,
        settings: EvSettings,
        *,
        phase_switch_delay_seconds: float = _PHASE_SWITCH_DELAY_SECONDS,
    ) -> None:
        self._client = client
        self._settings = settings
        self._phase_switch_delay_seconds = max(0.0, float(phase_switch_delay_seconds))
        self._phase_switch_target: str | None = None
        self._phase_switch_until_utc: datetime | None = None
        self._service_write_count = 0
        self._phase_switch_count = 0
        self._last_write_utc: datetime | None = None
        self._last_action: str | None = None
        self._last_command_key: tuple[str, str] | None = None
        self._command_attempts = 0
        self._write_errors = 0
        self._fault_until_utc: datetime | None = None
        self._last_error: str | None = None

    @property
    def enabled(self) -> bool:
        return self._settings.control_enabled and all(
            (
                self._settings.current_entity,
                self._settings.phase_mode_entity,
                self._settings.force_state_entity,
            )
        )

    @property
    def fault_active(self) -> bool:
        return self._fault_until_utc is not None and datetime.now(UTC) < self._fault_until_utc

    @property
    def consecutive_failures(self) -> int:
        return max(max(0, self._command_attempts - 1), self._write_errors)

    @property
    def last_error(self) -> str | None:
        return self._last_error

    async def initialize(self) -> None:
        """Keep the charger stopped until the first authoritative plan is available."""
        if not self.enabled:
            await self._publish_status("disabled", reason="control_disabled")
            return
        _LOGGER.warning(
            "EV hardware control ENABLED: current=%s, phase=%s, force=%s, limits=%.0f-%.0f A",
            self._settings.current_entity,
            self._settings.phase_mode_entity,
            self._settings.force_state_entity,
            self._settings.min_charge_current_a,
            self._settings.max_charge_current_a,
        )
        await self.safe_stop("startup_safe_stop", force=True)

    async def shutdown(self) -> None:
        """Leave the charger stopped on a clean Energy Manager shutdown."""
        if self.enabled:
            await self.safe_stop("shutdown_safe_stop", force=True)

    async def apply_dispatch(self, result) -> None:
        """Apply the EV command generated by the current planner interval."""
        self._clear_expired_fault()
        if self.fault_active:
            await self._publish_fault_fallback("write_retry_cooldown")
            return
        ev_result = next((item for item in result.command_results if item.actuator_id == "ev"), None)
        if not self.enabled:
            await self._publish_status(
                "disabled",
                reason="control_disabled",
                requested_power_w=None if ev_result is None else ev_result.requested_power_w,
                accepted_power_w=None if ev_result is None else ev_result.accepted_power_w,
            )
            return
        if ev_result is None:
            await self.safe_stop("ev_command_unavailable")
            return
        if (
            ev_result.accepted_power_w <= 0.0
            or ev_result.phase_count not in {1, 3}
            or ev_result.current_a is None
            or ev_result.current_a <= 0.0
        ):
            await self.safe_stop(
                ev_result.reason or "planner_idle",
                requested_power_w=ev_result.requested_power_w,
                accepted_power_w=ev_result.accepted_power_w,
            )
            return

        target_current = int(round(float(ev_result.current_a)))
        minimum_current = math.ceil(self._settings.min_charge_current_a)
        maximum_current = math.floor(self._settings.max_charge_current_a)
        if not minimum_current <= target_current <= maximum_current:
            await self.safe_stop(
                "current_outside_configured_limits",
                requested_power_w=ev_result.requested_power_w,
                accepted_power_w=ev_result.accepted_power_w,
            )
            return

        target_phase = _PHASE_SINGLE if ev_result.phase_count == 1 else _PHASE_THREE
        await self._apply_charge_target(
            target_phase,
            target_current,
            requested_power_w=ev_result.requested_power_w,
            accepted_power_w=ev_result.accepted_power_w,
        )

    async def safe_stop(
        self,
        reason: str,
        *,
        requested_power_w: float | None = None,
        accepted_power_w: float | None = None,
        force: bool = False,
    ) -> None:
        """Force the charger into Don't charge and cancel any phase transition."""
        self._clear_expired_fault()
        self._phase_switch_target = None
        self._phase_switch_until_utc = None
        if not self.enabled:
            await self._publish_status("disabled", reason="control_disabled")
            return

        observed = await self._read_control_state()
        force_state = observed[2]
        error = observed[3]
        if error is not None and not force:
            await self._trip_fault(f"control_state_unavailable:{error}")
            await self._publish_status(
                "safe_fallback",
                reason=reason,
                requested_power_w=requested_power_w,
                accepted_power_w=accepted_power_w,
                desired_phase_count=0,
                desired_current_a=0,
                observed_current_a=observed[0],
                observed_phase_mode=observed[1],
                observed_force_state=force_state,
                acknowledged=False,
                error=self._last_error,
            )
            return
        write_performed = False
        if force or not _force_is_off(force_state):
            write_error = await self._write_select(self._settings.force_state_entity, _FORCE_DONT_CHARGE, "force_off")
            if write_error is not None:
                await self._publish_status(
                    "write_error",
                    reason=reason,
                    requested_power_w=requested_power_w,
                    accepted_power_w=accepted_power_w,
                    observed_current_a=observed[0],
                    observed_phase_mode=observed[1],
                    observed_force_state=force_state,
                    error=write_error,
                )
                return
            write_performed = True

        if _force_is_off(force_state) and not write_performed:
            self._reset_failure_tracking()
        await self._publish_status(
            "stopped",
            reason=reason,
            requested_power_w=requested_power_w,
            accepted_power_w=accepted_power_w,
            desired_phase_count=0,
            desired_current_a=0,
            observed_current_a=observed[0],
            observed_phase_mode=observed[1],
            observed_force_state=force_state,
            write_performed=write_performed,
            acknowledged=_force_is_off(force_state) and not write_performed,
            error=error,
        )

    async def _apply_charge_target(
        self,
        target_phase: str,
        target_current: int,
        *,
        requested_power_w: float,
        accepted_power_w: float,
    ) -> None:
        observed_current, observed_phase, observed_force, read_error = await self._read_control_state()
        desired_phase_count = 1 if target_phase == _PHASE_SINGLE else 3
        now = datetime.now(UTC)

        if read_error is not None:
            await self._trip_fault(f"control_state_unavailable:{read_error}")
            await self._publish_status(
                "safe_fallback",
                reason="control_state_unavailable",
                requested_power_w=requested_power_w,
                accepted_power_w=accepted_power_w,
                desired_phase_count=desired_phase_count,
                desired_current_a=target_current,
                observed_current_a=observed_current,
                observed_phase_mode=observed_phase,
                observed_force_state=observed_force,
                error=read_error,
            )
            return

        if self._phase_switch_target is not None:
            if target_phase != self._phase_switch_target:
                await self._start_phase_switch(
                    target_phase,
                    desired_phase_count,
                    target_current,
                    requested_power_w,
                    accepted_power_w,
                    observed_current,
                    observed_phase,
                    observed_force,
                    now,
                )
                return
            if self._phase_switch_until_utc is not None and now < self._phase_switch_until_utc:
                if not _force_is_off(observed_force):
                    error = await self._write_select(
                        self._settings.force_state_entity,
                        _FORCE_DONT_CHARGE,
                        "phase_switch_force_off",
                    )
                    if error is not None:
                        await self._publish_write_error(
                            "phase_switch_force_off",
                            error,
                            requested_power_w,
                            accepted_power_w,
                            desired_phase_count,
                            target_current,
                            observed_current,
                            observed_phase,
                            observed_force,
                        )
                        return
                await self._publish_status(
                    "phase_switch_wait",
                    reason="phase_change",
                    requested_power_w=requested_power_w,
                    accepted_power_w=accepted_power_w,
                    desired_phase_count=desired_phase_count,
                    desired_current_a=target_current,
                    observed_current_a=observed_current,
                    observed_phase_mode=observed_phase,
                    observed_force_state=observed_force,
                    acknowledged=False,
                )
                return
            if not _phase_matches(observed_phase, target_phase):
                await self._start_phase_switch(
                    target_phase,
                    desired_phase_count,
                    target_current,
                    requested_power_w,
                    accepted_power_w,
                    observed_current,
                    observed_phase,
                    observed_force,
                    now,
                )
                return
            self._phase_switch_target = None
            self._phase_switch_until_utc = None

        if not _phase_matches(observed_phase, target_phase):
            await self._start_phase_switch(
                target_phase,
                desired_phase_count,
                target_current,
                requested_power_w,
                accepted_power_w,
                observed_current,
                observed_phase,
                observed_force,
                now,
            )
            return

        write_performed = False
        if observed_current is None or not math.isclose(
            observed_current,
            float(target_current),
            abs_tol=_CURRENT_TOLERANCE_A,
        ):
            error = await self._write_number(self._settings.current_entity, target_current, "set_current")
            if error is not None:
                await self._best_effort_force_off()
                await self._publish_write_error(
                    "set_current",
                    error,
                    requested_power_w,
                    accepted_power_w,
                    desired_phase_count,
                    target_current,
                    observed_current,
                    observed_phase,
                    observed_force,
                )
                return
            write_performed = True

        if not _force_is_on(observed_force):
            error = await self._write_select(self._settings.force_state_entity, _FORCE_CHARGE, "force_charge")
            if error is not None:
                await self._best_effort_force_off()
                await self._publish_write_error(
                    "force_charge",
                    error,
                    requested_power_w,
                    accepted_power_w,
                    desired_phase_count,
                    target_current,
                    observed_current,
                    observed_phase,
                    observed_force,
                )
                return
            write_performed = True

        acknowledged = (
            not write_performed
            and _phase_matches(observed_phase, target_phase)
            and observed_current is not None
            and math.isclose(observed_current, float(target_current), abs_tol=_CURRENT_TOLERANCE_A)
            and _force_is_on(observed_force)
        )
        if acknowledged:
            self._reset_failure_tracking()
        await self._publish_status(
            "tracking" if acknowledged else "write_sent",
            reason="planner_command",
            requested_power_w=requested_power_w,
            accepted_power_w=accepted_power_w,
            desired_phase_count=desired_phase_count,
            desired_current_a=target_current,
            observed_current_a=observed_current,
            observed_phase_mode=observed_phase,
            observed_force_state=observed_force,
            write_performed=write_performed,
            acknowledged=acknowledged,
        )

    async def _start_phase_switch(
        self,
        target_phase: str,
        desired_phase_count: int,
        target_current: int,
        requested_power_w: float,
        accepted_power_w: float,
        observed_current: float | None,
        observed_phase: str | None,
        observed_force: str | None,
        now: datetime,
    ) -> None:
        if not _force_is_off(observed_force):
            error = await self._write_select(
                self._settings.force_state_entity,
                _FORCE_DONT_CHARGE,
                "phase_switch_force_off",
            )
            if error is not None:
                await self._publish_write_error(
                    "phase_switch_force_off",
                    error,
                    requested_power_w,
                    accepted_power_w,
                    desired_phase_count,
                    target_current,
                    observed_current,
                    observed_phase,
                    observed_force,
                )
                return

        error = await self._write_select(self._settings.phase_mode_entity, target_phase, "phase_switch")
        if error is not None:
            await self._publish_write_error(
                "phase_switch",
                error,
                requested_power_w,
                accepted_power_w,
                desired_phase_count,
                target_current,
                observed_current,
                observed_phase,
                observed_force,
            )
            return

        self._phase_switch_count += 1
        self._phase_switch_target = target_phase
        self._phase_switch_until_utc = now + timedelta(seconds=self._phase_switch_delay_seconds)
        await self._publish_status(
            "phase_switch_wait",
            reason="phase_change",
            requested_power_w=requested_power_w,
            accepted_power_w=accepted_power_w,
            desired_phase_count=desired_phase_count,
            desired_current_a=target_current,
            observed_current_a=observed_current,
            observed_phase_mode=observed_phase,
            observed_force_state=observed_force,
            write_performed=True,
            acknowledged=False,
        )

    async def _read_control_state(self) -> tuple[float | None, str | None, str | None, str | None]:
        current_entity = self._settings.current_entity
        phase_entity = self._settings.phase_mode_entity
        force_entity = self._settings.force_state_entity
        assert current_entity is not None
        assert phase_entity is not None
        assert force_entity is not None

        errors: list[str] = []
        current: float | None = None
        phase: str | None = None
        force: str | None = None
        for name, entity_id in (
            ("current", current_entity),
            ("phase", phase_entity),
            ("force", force_entity),
        ):
            try:
                state = await self._client.get_state(entity_id)
            except (HomeAssistantError, OSError, TimeoutError) as exc:
                errors.append(f"{name}:{exc}")
                continue
            raw = state.get("state")
            if name == "current":
                try:
                    parsed = float(raw)
                except (TypeError, ValueError):
                    errors.append(f"current:non_numeric:{raw!r}")
                    continue
                if not math.isfinite(parsed):
                    errors.append(f"current:non_finite:{raw!r}")
                    continue
                current = parsed
            elif name == "phase":
                phase = None if raw is None else str(raw).strip()
                if phase is None or phase.lower() in {"", "unknown", "unavailable"}:
                    errors.append(f"phase:unavailable:{raw!r}")
                    phase = None
            else:
                force = None if raw is None else str(raw).strip()
                if force is None or force.lower() in {"", "unknown", "unavailable"}:
                    errors.append(f"force:unavailable:{raw!r}")
                    force = None
        return current, phase, force, "; ".join(errors) or None

    async def _best_effort_force_off(self) -> None:
        if self.fault_active:
            return
        await self._write_select(self._settings.force_state_entity, _FORCE_DONT_CHARGE, "fail_safe_force_off")

    async def _write_number(self, entity_id: str | None, value: int, action: str) -> str | None:
        assert entity_id is not None
        key = (entity_id, str(value))
        guard_error = await self._guard_repeated_command(key)
        if guard_error is not None:
            return guard_error
        try:
            await self._client.call_service("number", "set_value", {"entity_id": entity_id, "value": value})
        except (HomeAssistantError, OSError, TimeoutError) as exc:
            return await self._record_write_error(action, exc)
        self._record_write(action, key)
        return None

    async def _write_select(self, entity_id: str | None, option: str, action: str) -> str | None:
        assert entity_id is not None
        key = (entity_id, option)
        guard_error = await self._guard_repeated_command(key)
        if guard_error is not None:
            return guard_error
        try:
            await self._client.call_service(
                "select",
                "select_option",
                {"entity_id": entity_id, "option": option},
            )
        except (HomeAssistantError, OSError, TimeoutError) as exc:
            return await self._record_write_error(action, exc)
        self._record_write(action, key)
        return None

    async def _guard_repeated_command(self, key: tuple[str, str]) -> str | None:
        self._clear_expired_fault()
        if self.fault_active:
            return "write_retry_cooldown"
        if self._last_command_key == key and self._command_attempts >= _MAX_COMMAND_ATTEMPTS:
            error = f"command_not_acknowledged:{key[0]}={key[1]}"
            await self._trip_fault(error)
            return error
        return None

    async def _record_write_error(self, action: str, exc: Exception) -> str:
        self._write_errors += 1
        self._last_error = str(exc)
        _LOGGER.error("EV %s write failed (%d/%d): %s", action, self._write_errors, _MAX_WRITE_ERRORS, exc)
        if self._write_errors >= _MAX_WRITE_ERRORS:
            await self._trip_fault(f"{action}_write_failed:{exc}")
        return str(exc)

    def _record_write(self, action: str, key: tuple[str, str]) -> None:
        self._service_write_count += 1
        self._last_write_utc = datetime.now(UTC)
        self._last_action = action
        self._write_errors = 0
        if self._last_command_key == key:
            self._command_attempts += 1
        else:
            self._last_command_key = key
            self._command_attempts = 1

    async def _trip_fault(self, error: str) -> None:
        self._last_error = error
        self._fault_until_utc = datetime.now(UTC) + timedelta(seconds=_FAULT_COOLDOWN_SECONDS)
        force_entity = self._settings.force_state_entity
        if force_entity is None:
            return
        try:
            await self._client.call_service(
                "select",
                "select_option",
                {"entity_id": force_entity, "option": _FORCE_DONT_CHARGE},
            )
        except (HomeAssistantError, OSError, TimeoutError) as exc:
            _LOGGER.error("EV fail-safe stop write failed: %s", exc)
            self._last_error = f"{error}; safe_stop_failed:{exc}"
            return
        self._service_write_count += 1
        self._last_write_utc = datetime.now(UTC)
        self._last_action = "fault_safe_stop"

    async def _publish_fault_fallback(self, reason: str) -> None:
        observed = await self._read_control_state()
        await self._publish_status(
            "safe_fallback",
            reason=reason,
            observed_current_a=observed[0],
            observed_phase_mode=observed[1],
            observed_force_state=observed[2],
            acknowledged=_force_is_off(observed[2]),
            error=self._last_error or observed[3],
        )

    def _clear_expired_fault(self) -> None:
        if self._fault_until_utc is not None and datetime.now(UTC) >= self._fault_until_utc:
            self._fault_until_utc = None
            self._command_attempts = 0
            self._write_errors = 0
            self._last_command_key = None

    def _reset_failure_tracking(self) -> None:
        self._command_attempts = 0
        self._write_errors = 0
        self._last_command_key = None
        self._fault_until_utc = None
        self._last_error = None

    async def _publish_write_error(
        self,
        action: str,
        error: str,
        requested_power_w: float,
        accepted_power_w: float,
        desired_phase_count: int,
        desired_current_a: int,
        observed_current_a: float | None,
        observed_phase_mode: str | None,
        observed_force_state: str | None,
    ) -> None:
        await self._publish_status(
            "write_error",
            reason=action,
            requested_power_w=requested_power_w,
            accepted_power_w=accepted_power_w,
            desired_phase_count=desired_phase_count,
            desired_current_a=desired_current_a,
            observed_current_a=observed_current_a,
            observed_phase_mode=observed_phase_mode,
            observed_force_state=observed_force_state,
            error=error,
        )

    async def _publish_status(
        self,
        status: str,
        *,
        reason: str,
        requested_power_w: float | None = None,
        accepted_power_w: float | None = None,
        desired_phase_count: int | None = None,
        desired_current_a: int | None = None,
        observed_current_a: float | None = None,
        observed_phase_mode: str | None = None,
        observed_force_state: str | None = None,
        write_performed: bool = False,
        acknowledged: bool | None = None,
        error: str | None = None,
    ) -> None:
        attributes: dict[str, Any] = {
            "friendly_name": "Energy Manager EV Control Status",
            "ev_control_version": EV_CONTROL_VERSION,
            "control_enabled": self.enabled,
            "hardware_writes": self.enabled,
            "current_entity": self._settings.current_entity,
            "phase_mode_entity": self._settings.phase_mode_entity,
            "force_state_entity": self._settings.force_state_entity,
            "min_charge_current_a": self._settings.min_charge_current_a,
            "max_charge_current_a": self._settings.max_charge_current_a,
            "phase_switch_delay_seconds": self._phase_switch_delay_seconds,
            "reason": reason,
            "requested_power_w": _round_optional(requested_power_w),
            "accepted_power_w": _round_optional(accepted_power_w),
            "desired_phase_count": desired_phase_count,
            "desired_current_a": desired_current_a,
            "observed_current_a": _round_optional(observed_current_a),
            "observed_phase_mode": observed_phase_mode,
            "observed_force_state": observed_force_state,
            "phase_transition_active": self._phase_switch_target is not None,
            "phase_transition_target": self._phase_switch_target,
            "phase_transition_until_utc": (
                self._phase_switch_until_utc.isoformat() if self._phase_switch_until_utc else None
            ),
            "write_performed": write_performed,
            "acknowledged": acknowledged,
            "service_write_count": self._service_write_count,
            "phase_switch_count": self._phase_switch_count,
            "last_write_utc": self._last_write_utc.isoformat() if self._last_write_utc else None,
            "last_action": self._last_action,
            "command_attempts": self._command_attempts,
            "write_error_count": self._write_errors,
            "max_retry_attempts": max(_MAX_COMMAND_ATTEMPTS, _MAX_WRITE_ERRORS),
            "fault_active": self.fault_active,
            "fault_until_utc": self._fault_until_utc.isoformat() if self._fault_until_utc else None,
            "last_error": self._last_error,
            "last_update_utc": datetime.now(UTC).isoformat(),
        }
        if error is not None:
            attributes["error"] = error
        await self._client.set_state(EV_CONTROL_STATUS_ENTITY, status, attributes)


def _phase_matches(observed: str | None, target: str) -> bool:
    if observed is None:
        return False
    normalized = observed.strip().lower()
    if target == _PHASE_SINGLE:
        return normalized in {"1", "1-phase", "1 phase", "single phase", "single-phase"}
    return normalized in {"2", "3-phase", "3 phase", "three phase", "three-phase"}


def _force_is_off(observed: str | None) -> bool:
    if observed is None:
        return False
    return observed.strip().lower() in {"1", "don't charge", "dont charge", "off"}


def _force_is_on(observed: str | None) -> bool:
    if observed is None:
        return False
    return observed.strip().lower() in {"2", "charge", "on"}


def _round_optional(value: float | None) -> float | None:
    return None if value is None else round(float(value), 1)
